{
  imports = [
    ./discord.nix
    ./firefox.nix
    ./thunderbird.nix
    ./texstudio.nix
    ./cinny.nix
    ./vscode.nix
    ./setzer.nix
    ./tuba.nix
    ./rnote.nix
    ./freecad.nix
    ./mediawriter.nix
    ./prusa-slicer.nix
    ./qbittorrent.nix
    ./libreoffice.nix
    ./bottles.nix
    ./bitwarden.nix
    ./xournalpp.nix
  ];
}
